[package]
name = "ftw"
version = "0.8.0"
authors = ["Michael Angelo Calimlim <macalimlim@gmail.com>"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/macalimlim/ftw"
description = "A CLI tool to manage your godot-rust projects!"
keywords = ["godot", "godot-rust"]
categories = ["command-line-utilities", "game-development"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.41", default-features = false }
cargo-edit = "0.7.0"
cargo-generate = "0.9.0"
clap = { version = "3.0.0-beta.2", default-features = false, features = [ "cargo", "color", "std" ] }
colored = "2.0.0"
command-macros = "0.2.9"
fs_extra = "1.2.0"
kstring = "1.0.1"
liquid = { version = "0.22.0", default-features = false, features = [ "stdlib" ] }
liquid-core = { version = "0.22.0", default-features = false }
nanoid = "0.4.0"
regex = { version = "1.4.5", default-features = false }
rust-ini = { version = "0.17.0", default-features = false }
strum = "0.21.0"
strum_macros = "0.21.1"
thiserror = "1.0.24"
voca_rs = "1.13.0"
walkdir = "2.3.2"

[dev-dependencies]
assert_cmd = "1.0.6"
cargo-edit = "0.7.0"
nanoid = "0.4.0"
predicates = { version = "1.0.7", default-features = false }
proptest = "1.0.0"
rusty-forkfork = "0.4.0"
